spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:leiloes
spring.datasource.username=sa
spring.datasource.password=teste

# jpa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.root=WARN

#http://localhost:8080/h2-console
#driver url: jdbc:h2:mem:alura-forum
#login: sa (sem senha) 

#logging.level.org.hibernate.SQL=DEBUG
